version: '3.3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=cadeaux
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "456"
      MYSQL_DATABASE: "mydatabase"
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: ['--default-authentication-plugin=mysql_native_password']
    networks:
      - app-network

volumes:
  db-data:


networks:
  app-network:
    driver: bridge