version: '3.3'

services:
  db:
    image: mysql:8
    container_name: cadeau_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "456"
      MYSQL_DATABASE: "gestion_cadeau"
   
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./mysql/init-user.sql:/docker-entrypoint-initdb.d/init-user.sql


    networks:
      - app-network

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '8084:80'
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: 123
      depends_on:
        - db
      networks:
        - app-network

        
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=gestion_cadeau
    depends_on:
      - db
    networks:
      - app-network

  frontend:
      build: ./frontend
      ports:
        - "8007:8000"
      depends_on:
        - db
      networks:
        - app-network
      volumes:
      - './frontend:/usr/src/app'

  

volumes:
  db-data:



networks:
  app-network:
    driver: bridge